version: '3'

vars:
  LD_FLAGS_WINDOWS: -H=windowsgui
  LD_FLAGS_EXTRA: '{{if eq OS "windows"}} {{.LD_FLAGS_WINDOWS}} {{else}}    {{end}}'

tasks:
  go_build:
    env:
      GO111MODULE: on
      CGO_ENABLED: 1
    cmds:
      #- go vet
      - rm -f target/batchai.0*
      - GOOS={{.GOOS}} GOARCH={{.GOARCH}} go build -trimpath -ldflags "-s -w -X main.Version={{.VERSION}} -X main.CommitId={{.COMMIT_ID}} {{.LD_FLAGS_EXTRA}}" -o target/batchai.{{.GOOS}}-{{.GOARCH}}{{exeExt}} ./cmd/batchai/main.go
      #- upx -9 -k -v target/batchai.{{.GOOS}}-{{.GOARCH}}{{exeExt}}
  mockgen:
    cmds:
      - task: rm
        vars:
           TARGET: pkg/{{.MOCK_PKG_DEST}}/{{.MOCK_DEST_FILE}}
      - mockgen -destination pkg/{{.MOCK_PKG_DEST}}/{{.MOCK_DEST_FILE}} -package test --build_flags=--mod=mod {{.PROJECT_PKG}}/pkg/{{.MOCK_PKG_SRC}} {{.MOCK_INTERFACE}}
  rm:
    cmds:
      - echo $PATH
      - '{{if eq OS "windows"}} powershell Remove-Item {{.TARGET}} -Force -Recurse {{else}} rm -rf {{.TARGET}} {{end}}'
  cp:
    cmds:
      - '{{if eq OS "windows"}} powershell Copy-Item {{.SRC}} {{.TARGET}} -Recurse {{else}} cp -rf  {{.SRC}} {{.TARGET}} {{end}}'
