version: '3'

env:
  GOOS: linux
  
tasks:
  linux:
    desc: release for linux
    cmds:
      - task: :base:go_build
        vars:
          GOARCH: amd64
      - task: :base:go_build
        vars:
          GOARCH: arm64
